books_api_book_create:
    path:     /create/{title}/{price}/{description}
    defaults: { _controller: booksapi.controller.index:createAction }

books_api_book_fetch:
    path:     /fetch/{id}
    defaults: { _controller: booksapi.controller.index:fetchAction }
